/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-sans)"],
        mono: ["var(--font-mono)"],
      },
      colors: {
        primary: "#1c1c1c",
        "primary-light": "rgba(28, 28, 28, 0.83)",
        success: "#16a34a",
        warning: "#d97706",
        error: "#dc2626",
        background: "var(--adlts-page)",
        card: "var(--adlts-surface)",
        "canvas": "var(--adlts-canvas)",
        "text-dark": "#1c1c1c",
        "text-light": "#5f5f5d",
        "adlts-navy-950": "var(--adlts-navy-950)",
        "adlts-navy-900": "var(--adlts-navy-900)",
        "adlts-navy-800": "var(--adlts-navy-800)",
        "text-main": "var(--adlts-ink-900)",
        "text-muted": "var(--adlts-ink-700)",
        "surface": "var(--adlts-surface)",
        "surface-soft": "var(--adlts-surface-soft)",
        "page": "var(--adlts-page)",
        "page-soft": "var(--adlts-page-soft)",
        "border-soft": "var(--adlts-border-strong)",
        "success-50": "var(--adlts-success-50)",
        "success-600": "var(--adlts-success-600)",
        "success-700": "var(--adlts-success-700)",
        "warning-50": "var(--adlts-warning-50)",
        "warning-600": "var(--adlts-warning-600)",
        "warning-700": "var(--adlts-warning-700)",
        "error-50": "var(--adlts-error-50)",
        "error-600": "var(--adlts-error-600)",
        "error-700": "var(--adlts-error-700)",
        "review-50": "var(--adlts-review-50)",
        "review-600": "var(--adlts-review-600)",
        "blue-50": "var(--adlts-blue-50)",
        "blue-100": "var(--adlts-blue-100)",
        "blue-200": "var(--adlts-blue-200)",
        "blue-300": "var(--adlts-blue-300)",
        "blue-400": "var(--adlts-blue-400)",
        "blue-500": "var(--adlts-blue-500)",
        "blue-600": "var(--adlts-blue-600)",
        "blue-700": "var(--adlts-blue-700)",
        "blue-800": "var(--adlts-blue-800)",
        "blue-900": "var(--adlts-blue-900)",
        "ink-50": "var(--adlts-ink-500)",
        "ink-300": "var(--adlts-ink-300)",
        "ink-400": "var(--adlts-ink-400)",
        "ink-500": "var(--adlts-ink-500)",
        "ink-600": "var(--adlts-ink-600)",
        "ink-700": "var(--adlts-ink-700)",
        "ink-800": "var(--adlts-ink-800)",
        "ink-900": "var(--adlts-ink-900)",
        "ink-950": "var(--adlts-ink-950)",
        "adlts-green": "var(--adlts-civic-green)",
        "adlts-gold": "var(--adlts-civic-gold)",
        "adlts-red": "var(--adlts-civic-red)",
        "focus": "var(--adlts-focus)",
        "focus-ring": "var(--adlts-focus-ring)",
      },
      spacing: {
        20: "80px",
        32: "128px",
        40: "160px",
        64: "256px",
        80: "320px",
        96: "384px",
        128: "512px",
        2.5: "10px",
        14: "56px",
        22: "88px",
        24: "96px",
        44: "176px",
        48: "192px",
        52: "208px",
      },
      borderRadius: {
        xs: "var(--adlts-radius-xs)",
        sm: "var(--adlts-radius-sm)",
        DEFAULT: "var(--adlts-radius-sm)",
        md: "var(--adlts-radius-md)",
        lg: "var(--adlts-radius-lg)",
        xl: "var(--adlts-radius-xl)",
        "2xl": "var(--adlts-radius-xl)",
        pill: "var(--adlts-radius-pill)",
      },
      boxShadow: {
        card: "var(--adlts-shadow-card)",
        "card-hover": "var(--adlts-shadow-card-hover)",
        popover: "var(--adlts-shadow-popover)",
      },
      transitionDuration: {
        fast: "var(--adlts-motion-fast)",
        base: "var(--adlts-motion-base)",
        smooth: "var(--adlts-motion-smooth)",
        slow: "var(--adlts-motion-slow)",
      },
      transitionTimingFunction: {
        standard: "var(--adlts-motion-ease-standard)",
        emphasized: "var(--adlts-motion-ease-emphasized)",
      },
      maxWidth: {
        "container-public": "var(--adlts-container-public)",
        "container-wide": "var(--adlts-container-wide)",
        "container-reading": "var(--adlts-container-reading)",
        "container-form": "var(--adlts-container-form)",
      },
    },
  },
  plugins: [],
};
