/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-sans)"],
        mono: ["var(--font-mono)"],
      },
      colors: {
        bg: "var(--bg)",
        surface: "var(--surface)",
        "surface-2": "var(--surface-2)",
        border: "var(--border)",
        "border-strong": "var(--border-strong)",
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "text-tertiary": "var(--text-tertiary)",
        accent: "var(--accent)",
        "accent-hover": "var(--accent-hover)",
        "accent-subtle": "var(--accent-subtle)",
        success: "var(--success)",
        "success-subtle": "var(--success-subtle)",
        warning: "var(--warning)",
        "warning-subtle": "var(--warning-subtle)",
        danger: "var(--danger)",
        "danger-subtle": "var(--danger-subtle)",
        neutral: "var(--neutral)",
        "neutral-subtle": "var(--neutral-subtle)",
        error: "var(--danger)",
        primary: "var(--text-primary)",
        "primary-light": "var(--text-secondary)",
        background: "var(--bg)",
        card: "var(--surface)",
        canvas: "var(--surface)",
        "text-dark": "var(--text-primary)",
        "text-light": "var(--text-secondary)",
        "adlts-navy-950": "var(--adlts-navy-950)",
        "adlts-navy-900": "var(--adlts-navy-900)",
        "adlts-navy-800": "var(--adlts-navy-800)",
        "text-main": "var(--adlts-ink-900)",
        "text-muted": "var(--adlts-ink-700)",
        "surface": "var(--adlts-surface)",
        "surface-soft": "var(--adlts-surface-soft)",
        "page": "var(--adlts-page)",
        "page-soft": "var(--adlts-page-soft)",
        "border-soft": "var(--adlts-border-strong)",
        "success-50": "var(--adlts-success-50)",
        "success-600": "var(--adlts-success-600)",
        "success-700": "var(--adlts-success-700)",
        "warning-50": "var(--adlts-warning-50)",
        "warning-600": "var(--adlts-warning-600)",
        "warning-700": "var(--adlts-warning-700)",
        "error-50": "var(--adlts-error-50)",
        "error-600": "var(--adlts-error-600)",
        "error-700": "var(--adlts-error-700)",
        "review-50": "var(--adlts-review-50)",
        "review-600": "var(--adlts-review-600)",
        "blue-50": "var(--adlts-blue-50)",
        "blue-100": "var(--adlts-blue-100)",
        "blue-200": "var(--adlts-blue-200)",
        "blue-300": "var(--adlts-blue-300)",
        "blue-400": "var(--adlts-blue-400)",
        "blue-500": "var(--adlts-blue-500)",
        "blue-600": "var(--adlts-blue-600)",
        "blue-700": "var(--adlts-blue-700)",
        "blue-800": "var(--adlts-blue-800)",
        "blue-900": "var(--adlts-blue-900)",
        "ink-50": "var(--adlts-ink-500)",
        "ink-300": "var(--adlts-ink-300)",
        "ink-400": "var(--adlts-ink-400)",
        "ink-500": "var(--adlts-ink-500)",
        "ink-600": "var(--adlts-ink-600)",
        "ink-700": "var(--adlts-ink-700)",
        "ink-800": "var(--adlts-ink-800)",
        "ink-900": "var(--adlts-ink-900)",
        "ink-950": "var(--adlts-ink-950)",
        "adlts-green": "var(--adlts-civic-green)",
        "adlts-gold": "var(--adlts-civic-gold)",
        "adlts-red": "var(--adlts-civic-red)",
        "focus": "var(--adlts-focus)",
        "focus-ring": "var(--adlts-focus-ring)",
      },
      spacing: {
        20: "80px",
        32: "128px",
        40: "160px",
        64: "256px",
        80: "320px",
        96: "384px",
        128: "512px",
        2.5: "10px",
        14: "56px",
        22: "88px",
        24: "96px",
        44: "176px",
        48: "192px",
        52: "208px",
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        DEFAULT: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-lg)",
        "2xl": "var(--radius-lg)",
        pill: "var(--radius-md)",
      },
      boxShadow: {
        card: "var(--shadow-resting)",
        "card-hover": "var(--shadow-resting)",
        popover: "var(--shadow-modal)",
      },
      transitionDuration: {
        fast: "var(--motion-fast)",
        base: "var(--motion-fast)",
        smooth: "var(--motion-fast)",
        slow: "var(--motion-fast)",
      },
      transitionTimingFunction: {
        standard: "var(--motion-ease)",
        emphasized: "var(--motion-ease)",
      },
      maxWidth: {
        "container-public": "var(--container-public)",
        "container-wide": "var(--container-wide)",
        "container-reading": "var(--container-reading)",
        "container-form": "var(--container-form)",
      },
    },
  },
  plugins: [],
};
